# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Screens/MyDesigner.h \
    ./Screens/project/GraphicsLibrary/Basic/Triangle.h \
    ./Screens/project/MathLibrary/Deformer/FFD.h \
    ./Screens/project/GraphicsLibrary/Mesh/QSegMesh.h \
    ./Screens/project/GraphicsLibrary/Mesh/QSurfaceMesh.h \
    ./Screens/project/Stacker/GCylinder.h \
    ./Screens/project/MathLibrary/Deformer/QFFD.h \
    ./Screens/project/GUI/MeshBrowser/QuickMeshViewer.h \
    ./Screens/project/GUI/MeshBrowser/QuickMesh.h \
    ./Screens/project/MathLibrary/Deformer/QControlPoint.h \
    ./Screens/project/MathLibrary/Deformer/VoxelDeformer.h \
    ./Screens/project/Stacker/HiddenViewer.h \
    ./Screens/project/Stacker/QManualDeformer.h \
    ./Screens/project/Stacker/Offset.h \
    ./Screens/drawCube.h \
    ./Screens/drawPlane.h \
    ./Screens/drawRoundRect.h \
    ./Screens/sphereDraw.h \
    ./Screens/Client.h \
    ./resource.h \
    ./userstudy.h \
    ./Screens/videoplayer/gui_player/VideoToolbar.h \
    ./Screens/videoplayer/gui_player/VideoWidget.h
SOURCES += ./Screens/MyDesigner.cpp \
    ./Screens/project/GL/GLee.c \
    ./Screens/project/GL/VBO/VBO.cpp \
    ./Screens/project/GraphicsLibrary/Basic/Circle.cpp \
    ./Screens/project/GraphicsLibrary/Basic/Line.cpp \
    ./Screens/project/GraphicsLibrary/Basic/Plane.cpp \
    ./Screens/project/GraphicsLibrary/Basic/Triangle.cpp \
    ./Screens/project/GraphicsLibrary/Mesh/QSegMesh.cpp \
    ./Screens/project/GraphicsLibrary/Mesh/QSurfaceMesh.cpp \
    ./Screens/project/GraphicsLibrary/Mesh/SurfaceMesh/IO_.cpp \
    ./Screens/project/GraphicsLibrary/Mesh/SurfaceMesh/IO_obj.cpp \
    ./Screens/project/GraphicsLibrary/Mesh/SurfaceMesh/IO_off.cpp \
    ./Screens/project/GraphicsLibrary/Mesh/SurfaceMesh/IO_stl.cpp \
    ./Screens/project/GraphicsLibrary/Mesh/SurfaceMesh/Surface_mesh.cpp \
    ./Screens/project/GraphicsLibrary/Skeleton/ClosedPolygon.cpp \
    ./Screens/project/GraphicsLibrary/Skeleton/GeneralizedCylinder.cpp \
    ./Screens/project/GraphicsLibrary/Skeleton/PriorityQueue.cpp \
    ./Screens/project/GraphicsLibrary/Skeleton/Skeleton.cpp \
    ./Screens/project/GraphicsLibrary/Skeleton/SkeletonExtract.cpp \
    ./Screens/project/GraphicsLibrary/SpacePartition/kdtree.cpp \
    ./Screens/project/GraphicsLibrary/SpacePartition/Octree.cpp \
    ./Screens/project/GraphicsLibrary/Voxel/Voxeler.cpp \
    ./Screens/project/GUI/MeshBrowser/QuickMeshViewer.cpp \
    ./Screens/project/MathLibrary/Bounding/BoundingBox.cpp \
    ./Screens/project/MathLibrary/Bounding/Box3.cpp \
    ./Screens/project/MathLibrary/Bounding/ConvexHull2.cpp \
    ./Screens/project/MathLibrary/Bounding/ConvexHull3.cpp \
    ./Screens/project/MathLibrary/Bounding/MinOBB2.cpp \
    ./Screens/project/MathLibrary/Bounding/MinOBB3.cpp \
    ./Screens/project/MathLibrary/Coordiantes/GCDeformation.cpp \
    ./Screens/project/MathLibrary/Deformer/FFD.cpp \
    ./Screens/project/MathLibrary/Deformer/QFFD.cpp \
    ./Screens/project/MathLibrary/Deformer/Skinning.cpp \
    ./Screens/project/MathLibrary/Deformer/VoxelDeformer.cpp \
    ./Screens/project/Stacker/ConcentricGroup.cpp \
    ./Screens/project/Stacker/ConstraintGraph.cpp \
    ./Screens/project/Stacker/Controller.cpp \
    ./Screens/project/Stacker/CoplanarGroup.cpp \
    ./Screens/project/Stacker/Cuboid.cpp \
    ./Screens/project/Stacker/EditPath.cpp \
    ./Screens/project/Stacker/GCylinder.cpp \
    ./Screens/project/Stacker/Group.cpp \
    ./Screens/project/Stacker/HiddenViewer.cpp \
    ./Screens/project/Stacker/HotSpot.cpp \
    ./Screens/project/Stacker/JointDetector.cpp \
    ./Screens/project/Stacker/LineJointGroup.cpp \
    ./Screens/project/Stacker/Numeric.cpp \
    ./Screens/project/Stacker/Offset.cpp \
    ./Screens/project/Stacker/PointJointGroup.cpp \
    ./Screens/project/Stacker/Primitive.cpp \
    ./Screens/project/Stacker/Propagator.cpp \
    ./Screens/project/Stacker/QManualDeformer.cpp \
    ./Screens/project/Stacker/ShapeState.cpp \
    ./Screens/project/Stacker/SymmetryGroup.cpp \
    ./Screens/project/Utility/ColorMap.cpp \
    ./Screens/project/Utility/SimpleDraw.cpp \
    ./Screens/solver/umfpack_solver/umfpack_all.cpp \
    ./Screens/Client.cpp \
    ./main.cpp \
    ./userstudy.cpp
FORMS += ./Screens/DesignWidget.ui \
    ./Screens/EvaluateWidget.ui \
    ./userstudyMainWindow.ui
RESOURCES += Resources/userstudyResource.qrc
